# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests V2
run-name: Unit Tests V2
on:
  push:
    branches:
      - 'main'
      - 'run-tests-with-py-files-changes'
  pull_request:
    branches: 
      - 'main'
    paths:
      - '**.py'
    types:
      - opened
      - synchronize

  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Do you want to run tests?'
        required: true
        type: boolean
        default: false


jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
    - name: Check if tests should run
      run: |
        if [ "${{ github.event.inputs.run-tests }}" != "true" ]; then
          echo "Tests are not running as per input."
          exit 0
        
    - name: Get latest repo content
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Build wheel
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build --wheel --outdir latest_build/
        echo WHEEL_FILE_PATH=$(ls latest_build/*.whl) >> $GITHUB_ENV
   
    - name: Install App from latest build
      run: |
        pip install $WHEEL_FILE_PATH
      
    - name: Install pytest
      run: |
        pip install pytest

    - name: Run Tests
      run:
        pytest --maxfail=1
        
        
    
