# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests from Wheel
run-name: Unit Tests from Wheel
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'
    paths:
      - '**.py'
    types:
      - opened
      - synchronize


jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:    
    - name: Get latest repo content
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Build wheel
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build --wheel --outdir latest_build/
        echo WHEEL_FILE_PATH=$(ls latest_build/*.whl) >> $GITHUB_ENV
   
    - name: Install pytest
      run: |
        pip install pytest

    - name: Install App from latest build
      run: |
        pip install $WHEEL_FILE_PATH
      
    - name: Run Tests
      run:
        pytest
        
        
    
